/**
 * @file variant_io.h
 * @author askn (K.Sato) multix.jp
 * @brief Macro/Micro API variant io header
 * @version 0.2
 * @date 2026-09-16
 * @copyright Copyright (c) 2026 askn37 at github.com
 * @link Product Potal : https://askn37.github.io/
 *         MIT License : https://askn37.github.io/LICENSE.html
 */

#pragma once
#if defined(ENABLE_MACRO_API) && !defined(DISABLE_MACRO_API) && (__AVR_ARCH__ >= 102)
#include <avr/io.h>
#define AVR_MEGAAVR_LIKE_MODERNAVR

#define __MSS_CLKCTRL_CLKSEL_OSCX__
#define __MSS_CLKCTRL_PDIV_DIVN__
#define __MSS_EVSYS_CH__
#define __MSS_AVRNOX_FUSES__

/* C Language Only */
#if !defined (__ASSEMBLER__)

/* Generator selector bit group configurations*/
#define EVSYS_CHANNEL_UPDI_SYNCH_gc       EVSYS_GENERATOR_UPDI_gc
#define EVSYS_CHANNEL_RTC_OVF_gc          EVSYS_GENERATOR_RTC_OVF_gc
#define EVSYS_CHANNEL_RTC_CMP_gc          EVSYS_GENERATOR_RTC_CMP_gc
#define EVSYS_CHANNEL_CCL_LUT0_gc         EVSYS_GENERATOR_CCL_LUT0_gc
#define EVSYS_CHANNEL_CCL_LUT1_gc         EVSYS_GENERATOR_CCL_LUT1_gc
#define EVSYS_CHANNEL_CCL_LUT2_gc         EVSYS_GENERATOR_CCL_LUT2_gc
#define EVSYS_CHANNEL_CCL_LUT3_gc         EVSYS_GENERATOR_CCL_LUT3_gc
#define EVSYS_CHANNEL_AC0_OUT_gc          EVSYS_GENERATOR_AC0_OUT_gc
#define EVSYS_CHANNEL_ADC0_RESRDY_gc      EVSYS_GENERATOR_ADC0_RESRDY_gc
#define EVSYS_CHANNEL_USART0_XCK_gc       EVSYS_GENERATOR_USART0_XCK_gc
#define EVSYS_CHANNEL_USART1_XCK_gc       EVSYS_GENERATOR_USART1_XCK_gc
#define EVSYS_CHANNEL_USART2_XCK_gc       EVSYS_GENERATOR_USART2_XCK_gc
#define EVSYS_CHANNEL_USART3_XCK_gc       EVSYS_GENERATOR_USART3_XCK_gc
#define EVSYS_CHANNEL_SPI0_SCK_gc         EVSYS_GENERATOR_SPI0_SCK_gc
#define EVSYS_CHANNEL_TCA0_OVF_LUNF_gc    EVSYS_GENERATOR_TCA0_OVF_LUNF_gc
#define EVSYS_CHANNEL_TCA0_HUNF_gc        EVSYS_GENERATOR_TCA0_HUNF_gc
#define EVSYS_CHANNEL_TCA0_CMP0_LCMP0_gc  EVSYS_GENERATOR_TCA0_CMP0_gc
#define EVSYS_CHANNEL_TCA0_CMP1_LCMP1_gc  EVSYS_GENERATOR_TCA0_CMP1_gc
#define EVSYS_CHANNEL_TCA0_CMP2_LCMP2_gc  EVSYS_GENERATOR_TCA0_CMP2_gc
#define EVSYS_CHANNEL_TCB0_CAPT_gc        EVSYS_GENERATOR_TCB0_CAPT_gc
#define EVSYS_CHANNEL_TCB1_CAPT_gc        EVSYS_GENERATOR_TCB1_CAPT_gc
#define EVSYS_CHANNEL_TCB2_CAPT_gc        EVSYS_GENERATOR_TCB2_CAPT_gc
#define EVSYS_CHANNEL_TCB3_CAPT_gc        EVSYS_GENERATOR_TCB3_CAPT_gc

#define EVSYS_CHANNEL0_RTC_PIT_DIV8192_gc EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL0_RTC_PIT_DIV4096_gc EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL0_RTC_PIT_DIV2048_gc EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL0_RTC_PIT_DIV1024_gc EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL1_RTC_PIT_DIV512_gc  EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL1_RTC_PIT_DIV256_gc  EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL1_RTC_PIT_DIV128_gc  EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL1_RTC_PIT_DIV64_gc   EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL2_RTC_PIT_DIV8192_gc EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL2_RTC_PIT_DIV4096_gc EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL2_RTC_PIT_DIV2048_gc EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL2_RTC_PIT_DIV1024_gc EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL3_RTC_PIT_DIV512_gc  EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL3_RTC_PIT_DIV256_gc  EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL3_RTC_PIT_DIV128_gc  EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL3_RTC_PIT_DIV64_gc   EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL4_RTC_PIT_DIV8192_gc EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL4_RTC_PIT_DIV4096_gc EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL4_RTC_PIT_DIV2048_gc EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL4_RTC_PIT_DIV1024_gc EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL5_RTC_PIT_DIV512_gc  EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL5_RTC_PIT_DIV256_gc  EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL5_RTC_PIT_DIV128_gc  EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL5_RTC_PIT_DIV64_gc   EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL6_RTC_PIT_DIV8192_gc EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL6_RTC_PIT_DIV4096_gc EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL6_RTC_PIT_DIV2048_gc EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL6_RTC_PIT_DIV1024_gc EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL7_RTC_PIT_DIV512_gc  EVSYS_GENERATOR_RTC_PIT0_gc
#define EVSYS_CHANNEL7_RTC_PIT_DIV256_gc  EVSYS_GENERATOR_RTC_PIT1_gc
#define EVSYS_CHANNEL7_RTC_PIT_DIV128_gc  EVSYS_GENERATOR_RTC_PIT2_gc
#define EVSYS_CHANNEL7_RTC_PIT_DIV64_gc   EVSYS_GENERATOR_RTC_PIT3_gc

#define EVSYS_CHANNEL0_PORTA_PIN0_gc      EVSYS_GENERATOR_PORT0_PIN0_gc
#define EVSYS_CHANNEL0_PORTA_PIN1_gc      EVSYS_GENERATOR_PORT0_PIN1_gc
#define EVSYS_CHANNEL0_PORTA_PIN2_gc      EVSYS_GENERATOR_PORT0_PIN2_gc
#define EVSYS_CHANNEL0_PORTA_PIN3_gc      EVSYS_GENERATOR_PORT0_PIN3_gc
#define EVSYS_CHANNEL0_PORTA_PIN4_gc      EVSYS_GENERATOR_PORT0_PIN4_gc
#define EVSYS_CHANNEL0_PORTA_PIN5_gc      EVSYS_GENERATOR_PORT0_PIN5_gc
#define EVSYS_CHANNEL0_PORTA_PIN6_gc      EVSYS_GENERATOR_PORT0_PIN6_gc
#define EVSYS_CHANNEL0_PORTA_PIN7_gc      EVSYS_GENERATOR_PORT0_PIN7_gc
#define EVSYS_CHANNEL0_PORTB_PIN0_gc      EVSYS_GENERATOR_PORT1_PIN0_gc
#define EVSYS_CHANNEL0_PORTB_PIN1_gc      EVSYS_GENERATOR_PORT1_PIN1_gc
#define EVSYS_CHANNEL0_PORTB_PIN2_gc      EVSYS_GENERATOR_PORT1_PIN2_gc
#define EVSYS_CHANNEL0_PORTB_PIN3_gc      EVSYS_GENERATOR_PORT1_PIN3_gc
#define EVSYS_CHANNEL0_PORTB_PIN4_gc      EVSYS_GENERATOR_PORT1_PIN4_gc
#define EVSYS_CHANNEL0_PORTB_PIN5_gc      EVSYS_GENERATOR_PORT1_PIN5_gc
#define EVSYS_CHANNEL0_PORTB_PIN6_gc      EVSYS_GENERATOR_PORT1_PIN6_gc
#define EVSYS_CHANNEL0_PORTB_PIN7_gc      EVSYS_GENERATOR_PORT1_PIN7_gc

#define EVSYS_CHANNEL1_PORTA_PIN0_gc      EVSYS_GENERATOR_PORT0_PIN0_gc
#define EVSYS_CHANNEL1_PORTA_PIN1_gc      EVSYS_GENERATOR_PORT0_PIN1_gc
#define EVSYS_CHANNEL1_PORTA_PIN2_gc      EVSYS_GENERATOR_PORT0_PIN2_gc
#define EVSYS_CHANNEL1_PORTA_PIN3_gc      EVSYS_GENERATOR_PORT0_PIN3_gc
#define EVSYS_CHANNEL1_PORTA_PIN4_gc      EVSYS_GENERATOR_PORT0_PIN4_gc
#define EVSYS_CHANNEL1_PORTA_PIN5_gc      EVSYS_GENERATOR_PORT0_PIN5_gc
#define EVSYS_CHANNEL1_PORTA_PIN6_gc      EVSYS_GENERATOR_PORT0_PIN6_gc
#define EVSYS_CHANNEL1_PORTA_PIN7_gc      EVSYS_GENERATOR_PORT0_PIN7_gc
#define EVSYS_CHANNEL1_PORTB_PIN0_gc      EVSYS_GENERATOR_PORT1_PIN0_gc
#define EVSYS_CHANNEL1_PORTB_PIN1_gc      EVSYS_GENERATOR_PORT1_PIN1_gc
#define EVSYS_CHANNEL1_PORTB_PIN2_gc      EVSYS_GENERATOR_PORT1_PIN2_gc
#define EVSYS_CHANNEL1_PORTB_PIN3_gc      EVSYS_GENERATOR_PORT1_PIN3_gc
#define EVSYS_CHANNEL1_PORTB_PIN4_gc      EVSYS_GENERATOR_PORT1_PIN4_gc
#define EVSYS_CHANNEL1_PORTB_PIN5_gc      EVSYS_GENERATOR_PORT1_PIN5_gc
#define EVSYS_CHANNEL1_PORTB_PIN6_gc      EVSYS_GENERATOR_PORT1_PIN6_gc
#define EVSYS_CHANNEL1_PORTB_PIN7_gc      EVSYS_GENERATOR_PORT1_PIN7_gc

#define EVSYS_CHANNEL2_PORTC_PIN0_gc      EVSYS_GENERATOR_PORT0_PIN0_gc
#define EVSYS_CHANNEL2_PORTC_PIN1_gc      EVSYS_GENERATOR_PORT0_PIN1_gc
#define EVSYS_CHANNEL2_PORTC_PIN2_gc      EVSYS_GENERATOR_PORT0_PIN2_gc
#define EVSYS_CHANNEL2_PORTC_PIN3_gc      EVSYS_GENERATOR_PORT0_PIN3_gc
#define EVSYS_CHANNEL2_PORTC_PIN4_gc      EVSYS_GENERATOR_PORT0_PIN4_gc
#define EVSYS_CHANNEL2_PORTC_PIN5_gc      EVSYS_GENERATOR_PORT0_PIN5_gc
#define EVSYS_CHANNEL2_PORTC_PIN6_gc      EVSYS_GENERATOR_PORT0_PIN6_gc
#define EVSYS_CHANNEL2_PORTC_PIN7_gc      EVSYS_GENERATOR_PORT0_PIN7_gc
#define EVSYS_CHANNEL2_PORTD_PIN0_gc      EVSYS_GENERATOR_PORT1_PIN0_gc
#define EVSYS_CHANNEL2_PORTD_PIN1_gc      EVSYS_GENERATOR_PORT1_PIN1_gc
#define EVSYS_CHANNEL2_PORTD_PIN2_gc      EVSYS_GENERATOR_PORT1_PIN2_gc
#define EVSYS_CHANNEL2_PORTD_PIN3_gc      EVSYS_GENERATOR_PORT1_PIN3_gc
#define EVSYS_CHANNEL2_PORTD_PIN4_gc      EVSYS_GENERATOR_PORT1_PIN4_gc
#define EVSYS_CHANNEL2_PORTD_PIN5_gc      EVSYS_GENERATOR_PORT1_PIN5_gc
#define EVSYS_CHANNEL2_PORTD_PIN6_gc      EVSYS_GENERATOR_PORT1_PIN6_gc
#define EVSYS_CHANNEL2_PORTD_PIN7_gc      EVSYS_GENERATOR_PORT1_PIN7_gc

#define EVSYS_CHANNEL3_PORTC_PIN0_gc      EVSYS_GENERATOR_PORT0_PIN0_gc
#define EVSYS_CHANNEL3_PORTC_PIN1_gc      EVSYS_GENERATOR_PORT0_PIN1_gc
#define EVSYS_CHANNEL3_PORTC_PIN2_gc      EVSYS_GENERATOR_PORT0_PIN2_gc
#define EVSYS_CHANNEL3_PORTC_PIN3_gc      EVSYS_GENERATOR_PORT0_PIN3_gc
#define EVSYS_CHANNEL3_PORTC_PIN4_gc      EVSYS_GENERATOR_PORT0_PIN4_gc
#define EVSYS_CHANNEL3_PORTC_PIN5_gc      EVSYS_GENERATOR_PORT0_PIN5_gc
#define EVSYS_CHANNEL3_PORTC_PIN6_gc      EVSYS_GENERATOR_PORT0_PIN6_gc
#define EVSYS_CHANNEL3_PORTC_PIN7_gc      EVSYS_GENERATOR_PORT0_PIN7_gc
#define EVSYS_CHANNEL3_PORTD_PIN0_gc      EVSYS_GENERATOR_PORT1_PIN0_gc
#define EVSYS_CHANNEL3_PORTD_PIN1_gc      EVSYS_GENERATOR_PORT1_PIN1_gc
#define EVSYS_CHANNEL3_PORTD_PIN2_gc      EVSYS_GENERATOR_PORT1_PIN2_gc
#define EVSYS_CHANNEL3_PORTD_PIN3_gc      EVSYS_GENERATOR_PORT1_PIN3_gc
#define EVSYS_CHANNEL3_PORTD_PIN4_gc      EVSYS_GENERATOR_PORT1_PIN4_gc
#define EVSYS_CHANNEL3_PORTD_PIN5_gc      EVSYS_GENERATOR_PORT1_PIN5_gc
#define EVSYS_CHANNEL3_PORTD_PIN6_gc      EVSYS_GENERATOR_PORT1_PIN6_gc
#define EVSYS_CHANNEL3_PORTD_PIN7_gc      EVSYS_GENERATOR_PORT1_PIN7_gc

#define EVSYS_CHANNEL4_PORTE_PIN0_gc      EVSYS_GENERATOR_PORT0_PIN0_gc
#define EVSYS_CHANNEL4_PORTE_PIN1_gc      EVSYS_GENERATOR_PORT0_PIN1_gc
#define EVSYS_CHANNEL4_PORTE_PIN2_gc      EVSYS_GENERATOR_PORT0_PIN2_gc
#define EVSYS_CHANNEL4_PORTE_PIN3_gc      EVSYS_GENERATOR_PORT0_PIN3_gc
#define EVSYS_CHANNEL4_PORTE_PIN4_gc      EVSYS_GENERATOR_PORT0_PIN4_gc
#define EVSYS_CHANNEL4_PORTE_PIN5_gc      EVSYS_GENERATOR_PORT0_PIN5_gc
#define EVSYS_CHANNEL4_PORTE_PIN6_gc      EVSYS_GENERATOR_PORT0_PIN6_gc
#define EVSYS_CHANNEL4_PORTE_PIN7_gc      EVSYS_GENERATOR_PORT0_PIN7_gc
#define EVSYS_CHANNEL4_PORTF_PIN0_gc      EVSYS_GENERATOR_PORT1_PIN0_gc
#define EVSYS_CHANNEL4_PORTF_PIN1_gc      EVSYS_GENERATOR_PORT1_PIN1_gc
#define EVSYS_CHANNEL4_PORTF_PIN2_gc      EVSYS_GENERATOR_PORT1_PIN2_gc
#define EVSYS_CHANNEL4_PORTF_PIN3_gc      EVSYS_GENERATOR_PORT1_PIN3_gc
#define EVSYS_CHANNEL4_PORTF_PIN4_gc      EVSYS_GENERATOR_PORT1_PIN4_gc
#define EVSYS_CHANNEL4_PORTF_PIN5_gc      EVSYS_GENERATOR_PORT1_PIN5_gc
#define EVSYS_CHANNEL4_PORTF_PIN6_gc      EVSYS_GENERATOR_PORT1_PIN6_gc
#define EVSYS_CHANNEL4_PORTF_PIN7_gc      EVSYS_GENERATOR_PORT1_PIN7_gc

#define EVSYS_CHANNEL5_PORTE_PIN0_gc      EVSYS_GENERATOR_PORT0_PIN0_gc
#define EVSYS_CHANNEL5_PORTE_PIN1_gc      EVSYS_GENERATOR_PORT0_PIN1_gc
#define EVSYS_CHANNEL5_PORTE_PIN2_gc      EVSYS_GENERATOR_PORT0_PIN2_gc
#define EVSYS_CHANNEL5_PORTE_PIN3_gc      EVSYS_GENERATOR_PORT0_PIN3_gc
#define EVSYS_CHANNEL5_PORTE_PIN4_gc      EVSYS_GENERATOR_PORT0_PIN4_gc
#define EVSYS_CHANNEL5_PORTE_PIN5_gc      EVSYS_GENERATOR_PORT0_PIN5_gc
#define EVSYS_CHANNEL5_PORTE_PIN6_gc      EVSYS_GENERATOR_PORT0_PIN6_gc
#define EVSYS_CHANNEL5_PORTE_PIN7_gc      EVSYS_GENERATOR_PORT0_PIN7_gc
#define EVSYS_CHANNEL5_PORTF_PIN0_gc      EVSYS_GENERATOR_PORT1_PIN0_gc
#define EVSYS_CHANNEL5_PORTF_PIN1_gc      EVSYS_GENERATOR_PORT1_PIN1_gc
#define EVSYS_CHANNEL5_PORTF_PIN2_gc      EVSYS_GENERATOR_PORT1_PIN2_gc
#define EVSYS_CHANNEL5_PORTF_PIN3_gc      EVSYS_GENERATOR_PORT1_PIN3_gc
#define EVSYS_CHANNEL5_PORTF_PIN4_gc      EVSYS_GENERATOR_PORT1_PIN4_gc
#define EVSYS_CHANNEL5_PORTF_PIN5_gc      EVSYS_GENERATOR_PORT1_PIN5_gc
#define EVSYS_CHANNEL5_PORTF_PIN6_gc      EVSYS_GENERATOR_PORT1_PIN6_gc
#define EVSYS_CHANNEL5_PORTF_PIN7_gc      EVSYS_GENERATOR_PORT1_PIN7_gc

/* Software event on channels select bit group configurations */
#define EVSYS_SWEVENTA_CH0_gc   EVSYS_STROBE0_EV_STROBE_CH0_gc
#define EVSYS_SWEVENTA_CH1_gc   EVSYS_STROBE0_EV_STROBE_CH1_gc
#define EVSYS_SWEVENTA_CH2_gc   EVSYS_STROBE0_EV_STROBE_CH2_gc
#define EVSYS_SWEVENTA_CH3_gc   EVSYS_STROBE0_EV_STROBE_CH3_gc
#define EVSYS_SWEVENTA_CH4_gc   EVSYS_STROBE0_EV_STROBE_CH4_gc
#define EVSYS_SWEVENTA_CH5_gc   EVSYS_STROBE0_EV_STROBE_CH5_gc
#define EVSYS_SWEVENTA_CH6_gc   EVSYS_STROBE0_EV_STROBE_CH6_gc
#define EVSYS_SWEVENTA_CH7_gc   EVSYS_STROBE0_EV_STROBE_CH7_gc

/* User channel select */
#define EVSYS_USER_OFF_gc       EVSYS_CHANNEL_OFF_gc
#define EVSYS_USER_CHANNEL0_gc  EVSYS_CHANNEL_CHANNEL0_gc
#define EVSYS_USER_CHANNEL1_gc  EVSYS_CHANNEL_CHANNEL1_gc
#define EVSYS_USER_CHANNEL2_gc  EVSYS_CHANNEL_CHANNEL2_gc
#define EVSYS_USER_CHANNEL3_gc  EVSYS_CHANNEL_CHANNEL3_gc
#define EVSYS_USER_CHANNEL4_gc  EVSYS_CHANNEL_CHANNEL4_gc
#define EVSYS_USER_CHANNEL5_gc  EVSYS_CHANNEL_CHANNEL5_gc
#define EVSYS_USER_CHANNEL6_gc  EVSYS_CHANNEL_CHANNEL6_gc
#define EVSYS_USER_CHANNEL7_gc  EVSYS_CHANNEL_CHANNEL7_gc

/* CCL Look-Up Table 0 Signals select */
typedef enum PORTMUX_LUT0_enum
{
    PORTMUX_LUT0_DEFAULT_gc = (0x00<<0),  /* Out: PA3 In: PA0, PA1, PA2 */
    PORTMUX_LUT0_ALT1_gc    = (0x01<<0)   /* Out: PA6 In: PA0, PA1, PA2 */
} PORTMUX_LUT0_t;

/* CCL Look-Up Table 1 Signals select */
typedef enum PORTMUX_LUT1_enum
{
    PORTMUX_LUT1_DEFAULT_gc = (0x00<<1),  /* Out: PC3 In: PC0, PC1, PC2 */
    PORTMUX_LUT1_ALT1_gc    = (0x01<<1),  /* Out: PC6 In: PC0, PC1, PC2 */
} PORTMUX_LUT1_t;

/* CCL Look-Up Table 2 Signals select */
typedef enum PORTMUX_LUT2_enum
{
    PORTMUX_LUT2_DEFAULT_gc = (0x00<<2),  /* Out: PD3 In: PD0, PD1, PD2 */
    PORTMUX_LUT2_ALT1_gc    = (0x01<<2)   /* Out: PD6 In: PD0, PD1, PD2 */
} PORTMUX_LUT2_t;

/* Clock Select */
typedef enum RTC_CLKSEL_ALT_enum
{
    RTC_CLKSEL_OSC32K_gc    = (0x00<<0),  /* 32.768 kHz from OSC32K */
    RTC_CLKSEL_OSC1K_gc     = (0x01<<0),  /* 1.024 kHz from OSC32K */
    RTC_CLKSEL_XOSC32K_gc   = (0x02<<0)   /* 32.768 kHz from XOSC32K */
} RTC_CLKSEL_ALT_t;

/* Event Action A select */
typedef enum TCA_SINGLE_EVACTA_enum
{
    TCA_SINGLE_EVACTA_CNT_POSEDGE_gc  = (0x00<<1),  /* Count on positive edge event */
    TCA_SINGLE_EVACTA_CNT_ANYEDGE_gc  = (0x01<<1),  /* Count on any edge event */
    TCA_SINGLE_EVACTA_CNT_HIGHLVL_gc  = (0x02<<1),  /* Count on prescaled clock while event line is 1. */
    TCA_SINGLE_EVACTA_UPDOWN_gc       = (0x03<<1)   /* Count on prescaled clock. Event controls count direction. Up-count when event line is 0, down-count when event line is 1. */
} TCA_SINGLE_EVACTA_t;

/* Clock Select */
typedef enum TCB_CLKSEL_ALT_enum
{
    TCB_CLKSEL_DIV1_gc = (0x00<<1),      /* CLK_PER */
    TCB_CLKSEL_DIV2_gc = (0x01<<1),      /* CLK_PER/2 */
    TCB_CLKSEL_TCA0_gc = (0x02<<1)       /* Use CLK_TCA from TCA0 */
} TCB_CLKSEL_ALT_t;

/* RS485 Mode internal transmitter select */
typedef enum USART_RS485_ALT_enum
{
    USART_RS485_DISABLE_gc  = (0x00<<0),  /* RS485 Mode disabled */
    USART_RS485_ENABLE_gc   = (0x01<<0)   /* RS485 Mode enabled */
} USART_RS485_ALT_t;

#endif /* !defined (__ASSEMBLER__) */

/* EVSYS - Event System */
#define EVSYS_SWEVENTA          EVSYS_STROBE
#define EVSYS_USERADC0START     EVSYS_USERADC0
#define EVSYS_USEREVSYSEVOUTA   EVSYS_USEREVOUTA
#define EVSYS_USEREVSYSEVOUTB   EVSYS_USEREVOUTB
#define EVSYS_USEREVSYSEVOUTC   EVSYS_USEREVOUTC
#define EVSYS_USEREVSYSEVOUTD   EVSYS_USEREVOUTD
#define EVSYS_USEREVSYSEVOUTE   EVSYS_USEREVOUTE
#define EVSYS_USEREVSYSEVOUTF   EVSYS_USEREVOUTF
#define EVSYS_USERUSART0IRDA    EVSYS_USERUSART0
#define EVSYS_USERUSART1IRDA    EVSYS_USERUSART1
#define EVSYS_USERUSART2IRDA    EVSYS_USERUSART2
#define EVSYS_USERUSART3IRDA    EVSYS_USERUSART3
#define EVSYS_USERTCA0CNTA      EVSYS_USERTCA0
#define EVSYS_USERTCB0CAPT      EVSYS_USERTCB0
#define EVSYS_USERTCB1CAPT      EVSYS_USERTCB1
#define EVSYS_USERTCB2CAPT      EVSYS_USERTCB2
#define EVSYS_USERTCB3CAPT      EVSYS_USERTCB3

/* EVSYS.SWEVENTA  bit masks and bit positions */
#define EVSYS_SWEVENTA_gm       0xFF    /* Software event on channel select group mask. */
#define EVSYS_SWEVENTA_gp       0       /* Software event on channel select group position. */
#define EVSYS_SWEVENTA_0_bm     (1<<0)  /* Software event on channel select bit 0 mask. */
#define EVSYS_SWEVENTA_0_bp     0       /* Software event on channel select bit 0 position. */
#define EVSYS_SWEVENTA_1_bm     (1<<1)  /* Software event on channel select bit 1 mask. */
#define EVSYS_SWEVENTA_1_bp     1       /* Software event on channel select bit 1 position. */
#define EVSYS_SWEVENTA_2_bm     (1<<2)  /* Software event on channel select bit 2 mask. */
#define EVSYS_SWEVENTA_2_bp     2       /* Software event on channel select bit 2 position. */
#define EVSYS_SWEVENTA_3_bm     (1<<3)  /* Software event on channel select bit 3 mask. */
#define EVSYS_SWEVENTA_3_bp     3       /* Software event on channel select bit 3 position. */
#define EVSYS_SWEVENTA_4_bm     (1<<4)  /* Software event on channel select bit 4 mask. */
#define EVSYS_SWEVENTA_4_bp     4       /* Software event on channel select bit 4 position. */
#define EVSYS_SWEVENTA_5_bm     (1<<5)  /* Software event on channel select bit 5 mask. */
#define EVSYS_SWEVENTA_5_bp     5       /* Software event on channel select bit 5 position. */
#define EVSYS_SWEVENTA_6_bm     (1<<6)  /* Software event on channel select bit 6 mask. */
#define EVSYS_SWEVENTA_6_bp     6       /* Software event on channel select bit 6 position. */
#define EVSYS_SWEVENTA_7_bm     (1<<7)  /* Software event on channel select bit 7 mask. */
#define EVSYS_SWEVENTA_7_bp     7       /* Software event on channel select bit 7 position. */


/* Other Alias and Dummy */
#define TCA_SINGLE_RUNSTDBY_bm  0       /* Run in Standby bit mask. (dummy) */
#define TCA_SINGLE_RUNSTDBY_bp  7       /* Run in Standby bit position. */
#define TCA_SPLIT_RUNSTDBY_bm   0       /* Run in Standby bit mask. (dummy) */
#define TCA_SPLIT_RUNSTDBY_bp   7       /* Run in Standby bit position. */
#define TCB_CASCADE_bm          0       /* Cascade two timers bit mask. (dummy) */
#define TCB_CASCADE_bp          5       /* Cascade two timers bit position. */

#define TCA_SINGLE_CNTAEI_bm    (1<<0)  /* Count on Event Input A bit mask. */
#define TCA_SINGLE_CNTAEI_bp    0       /* Count on Event Input A bit position. */

#define SWEVENTA        STROBE
#define USERADC0START   USERADC0
#define USEREVSYSEVOUTA USEREVOUTA
#define USEREVSYSEVOUTB USEREVOUTB
#define USEREVSYSEVOUTC USEREVOUTC
#define USEREVSYSEVOUTD USEREVOUTD
#define USEREVSYSEVOUTE USEREVOUTE
#define USEREVSYSEVOUTF USEREVOUTF
#define USERUSART0IRDA  USERUSART0
#define USERUSART1IRDA  USERUSART1
#define USERUSART2IRDA  USERUSART2
#define USERUSART3IRDA  USERUSART3
#define USERTCA0CNTA    USERTCA0
#define USERTCB0CAPT    USERTCB0
#define USERTCB1CAPT    USERTCB1
#define USERTCB2CAPT    USERTCB2
#define USERTCB3CAPT    USERTCB3

#include <api/macro_sugar.h>
#endif

// end of code
